# swiftmailer:
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }

swiftmailer: 
    transport: gmail 
    host: smtp.gmail.com 
    port: 465 
    auth_mode: login 
    username: hosnibaili1987@gmail.com 
    password: rabbim3aya 
    encryption: ssl 
    stream_options: 
        ssl: 
            allow_self_signed: true 
            verify_peer: false 
            verify_peer_name: false
